name: getsecure
description: Secure links for limited time access with simple md5 hash. Generate time-limited URLs with hash-based protection.
version: 2.0.0
repository: https://github.com/TestOrganizationPleaseIgnore/getsecure-dart
homepage: https://github.com/TestOrganizationPleaseIgnore/getsecure-dart
documentation: https://github.com/TestOrganizationPleaseIgnore/getsecure-dart/blob/main/README.md

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  crypto: ^3.0.3
  args: ^2.4.2

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
  melos: ^6.3.2
  coverage: ^1.11.1

topics:
  - security
  - url
  - hash
  - md5

melos:
  command:
    version:
      changelogCommitBodies:
        include: true
        onlyBreaking: false
